baseurl = "https://daniilidis-group.github.io/grasp_multicam/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "GRASP MultiCam"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[Params]
    # Souce Code repository section
    description = ""
    github_repository = "https://github.com/daniilidis-group/grasp_multicam"
#    version = "0.2.1"
    home_link = "https://daniilidis-group.github.io/grasp_multicam/"
    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    #    github_doc_repository = "https://github.com/daniilidis-group/grasp_multicam"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification

    # Theme settings section
    dateformat = "" # default "2 Jan 2006"
    
    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar
    # path name excluded from documentation menu
    menu_exclusion = ["archives", "archive", "blog", "entry", "post", "posts"]
    
    PublishDate = 2021-04-06T21:07:13+01:00

# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false
